Mongos must reach a valid config server before deploying

diff --git a/jobs/mongos/templates/bin/pre-start b/jobs/mongos/templates/bin/pre-start
--- a/jobs/mongos/templates/bin/pre-start
+++ b/jobs/mongos/templates/bin/pre-start
@@ -14,9 +14,36 @@ else
   export MONGO_CMD="${JOBS_COMMON_DIR}/bin/mongo-ssl.sh"
 fi
 
+# waiting for cfgsvr availability
+_timeout=${property_deployment_timeout}
+reached=0
+while [ ${_timeout} -gt 0 ] && [ ${reached} -ne 1 ]
+do
+
+	for cfgsvr in $(echo ${deployment_cfgsvr_config}|tr -s "," " ")
+	do
+		cfgsvr_ip=$(echo ${cfgsvr}|cut -d":" -f1)
+		cfgsvr_port=$(echo ${cfgsvr}|cut -d":" -f2)
+		if  nc -z "${cfgsvr_ip}" "${cfgsvr_port}"
+		then
+			[ ${reached} -eq 0 ] && reached=1
+		fi
+	done
+	if [ ${reached} -eq 0 ]
+	then
+		sleep 1
+		_timeout=$(($_timeout-1))
+	fi
+done
+[ ${_timeout} -le 0 ] \
+			&& echo "Cannot connect to config servers. Timeout reached" \
+			&& exit 1
+
 system_update            # Updating system mandatories
 rights_and_directories   # Create Mongodb directories and update rights on keyfile
 
 export MONGO_CMD_PARAM="--quiet"
+
+${JOB_DIR}/bin/mongos_ctl start 
 
 exit 0
