Make pre-start script more 'readable'

diff --git a/jobs/mongod/templates/bin/pre-start.erb b/jobs/mongod/templates/bin/pre-start.erb
--- a/jobs/mongod/templates/bin/pre-start.erb
+++ b/jobs/mongod/templates/bin/pre-start.erb
@@ -1,8 +1,7 @@
 #!/bin/bash
-set -eux
-#set -x
+set -eu
 
-source `dirname $(readlink --canonicalize-existing $0)`/setenv
+source `dirname $(readlink -f $0)`/setenv
 
 <%-
 if p("node_role") == "rs" || p("node_role") == "sa"
@@ -23,199 +22,231 @@ export MONGO_CMD="/var/vcap/jobs/${JOB_NAME}/bin/mongo.sh"
 export MONGO_CMD="/var/vcap/jobs/${JOB_NAME}/bin/mongo-ssl.sh"
 <%- end -%>
 
+
+####################### List the nodes actually referenced in replicaset ########################
 get_actual_members()
 {
-  m_list=""
-  for i in `${MONGO_CMD} --host rs0/<%= mongo_current_ip %>  ${MONGO_CMD_PARAM} --eval 'rs.status().members' \
-      | grep name | tr -s [:space:] | tr -d '"' | cut -d ":" -f2`
-  do
-    m_list="$m_list $i"
-  done
-  echo $m_list
+    m_list=""
+    for i in `${MONGO_CMD} --host rs0/<%= mongo_current_ip %>:<%= mongo_DbTypeport %> ${MONGO_CMD_PARAM} --eval 'rs.status().members' \
+        | grep name | tr -s [:space:] | tr -d '"' | cut -d ":" -f2`
+    do
+      m_list="$m_list $i"
+    done
+    echo $m_list
 }
+#################################################################################################
 
-start_bs()
+######################## Start mongod process in no-auth mode ###################################
+start_mongod_noauth()
 {
-  # Stopping eventually running instance
-  if [ -f $PIDFILE ]
-    then
-    [ `ps -p $(cat $PIDFILE)|wc -l` -gt 1 ] && kill_and_wait $PIDFILE
-  fi
-
-  pid_guard $PIDFILE ${JOB_NAME}
-
-  # start mongod without auth
-  su -m vcap -c "$MONGODB_BIN/mongod --config $MONGODB_CONF/mongod_bootstrap.conf --pidfilepath $PIDFILE"
-}
-
-sys_update()
-{
-  # creating needed directories
-  for dir in $RUN_DIR $LOG_DIR $TMP_DIR $STORE_DIR $DATA_DIR
-  do
-    mkdir -p ${dir}
-    chown vcap:vcap ${dir}
-    chmod 775 ${dir}
-  done
-
-  # updating vcap limits
-  if [ -f /etc/security/limits.conf ]
-  then
-    if [ `grep "$(cat $JOB_DIR/config/vcap_limits.conf)" /etc/security/limits.conf|wc -l` -eq 0 ]
-    then
-      cat $JOB_DIR/config/vcap_limits.conf >> /etc/security/limits.conf
-    fi
-  # Allow limits apply without rebooting
-    if [ -f /etc/pam.d/common-session ]
-    then
-      if [ `grep "^session required pam_limits.so" /etc/pam.d/common-session|wc -l` -eq 0 ]
+    # Stopping eventually running instance
+    if [ -f $PIDFILE ]
       then
-        echo "# Allow limits apply without rebooting" >> /etc/pam.d/common-session
-        echo "session required pam_limits.so" >> /etc/pam.d/common-session
+      [ `ps -p $(cat $PIDFILE)|wc -l` -gt 1 ] && kill_and_wait $PIDFILE
+    fi
+
+    pid_guard $PIDFILE ${JOB_NAME}
+
+    # start mongod without auth
+    su -m vcap -c "$MONGODB_BIN/mongod --config $MONGODB_CONF/mongod_bootstrap.conf  --pidfilepath $PIDFILE"
+}
+################################################################################################
+
+######################## Start mongod process with authentication ##############################
+start_mongod_with_auth()
+{
+
+    echo "=============> Starting with authentication"
+    # Stopping eventually running instance
+    if [ -f $PIDFILE ]
+      then
+      [ `ps -p $(cat $PIDFILE)|wc -l` -gt 1 ] && kill_and_wait $PIDFILE
+    fi
+
+    pid_guard $PIDFILE ${JOB_NAME}
+
+    # start mongod without auth
+    su -m vcap -c "$MONGODB_BIN/mongod --config $MONGODB_CONF/mongod.conf --pidfilepath $PIDFILE"
+}
+################################################################################################
+
+
+###################### Perform the OS mandatories ##############################################
+system_update()
+{
+    # creating needed directories
+    for dir in $RUN_DIR $LOG_DIR $TMP_DIR $STORE_DIR $DATA_DIR
+    do
+      mkdir -p ${dir}
+      chown vcap:vcap ${dir}
+      chmod 775 ${dir}
+    done
+
+    # updating vcap limits
+    if [ -f /etc/security/limits.conf ]
+    then
+      if [ `grep "$(cat $JOB_DIR/config/vcap_limits.conf)" /etc/security/limits.conf|wc -l` -eq 0 ]
+      then
+        cat $JOB_DIR/config/vcap_limits.conf >> /etc/security/limits.conf
+      fi
+    # Allow limits apply without rebooting
+      if [ -f /etc/pam.d/common-session ]
+      then
+        if [ `grep "^session required pam_limits.so" /etc/pam.d/common-session|wc -l` -eq 0 ]
+        then
+          echo "# Allow limits apply without rebooting" >> /etc/pam.d/common-session
+          echo "session required pam_limits.so" >> /etc/pam.d/common-session
+        fi
       fi
     fi
-  fi
 
-  # disabeling transparent_hugepage
-  if [ -d /sys/kernel/mm/transparent_hugepage ]; then
-        thp_path=/sys/kernel/mm/transparent_hugepage
-  elif [ -d /sys/kernel/mm/redhat_transparent_hugepage ]; then
-        thp_path=/sys/kernel/mm/redhat_transparent_hugepage
-  else
-        return 0
-  fi
+    # disabeling transparent_hugepage
+    if [ -d /sys/kernel/mm/transparent_hugepage ]; then
+          thp_path=/sys/kernel/mm/transparent_hugepage
+    elif [ -d /sys/kernel/mm/redhat_transparent_hugepage ]; then
+          thp_path=/sys/kernel/mm/redhat_transparent_hugepage
+    else
+          return 0
+    fi
 
-  echo 'never' > ${thp_path}/enabled
-  echo 'never' > ${thp_path}/defrag
-  unset thp_path
+    echo 'never' > ${thp_path}/enabled
+    echo 'never' > ${thp_path}/defrag
+    unset thp_path
 }
+################################################################################################
 
+######################## Look for an existing Primary node #####################################
 check_master()
 {
-  # looking for already created master node
-  Master=""
-  for Server in $(echo <%= mongo_rsconfig -%>|tr -s "," " ")
-  do
+    # looking for already created master node
+    Master=""
+    for Server in $(echo <%= mongo_rsconfig -%>|tr -s "," " ")
+    do
 
-    if [ "`${MONGO_CMD} --host $Server \
-        ${MONGO_CMD_PARAM} --eval 'db.isMaster().ismaster' 2>/dev/null`" == "true" ]
-    then
-      Master=$Server
-    else
-      if [ "`${MONGO_CMD} --host $Server -u '<%= p("root_username") %>' \
-          -p '<%= p("root_password") %>' --authenticationDatabase admin \
+      if [ "`${MONGO_CMD} --host $Server \
           ${MONGO_CMD_PARAM} --eval 'db.isMaster().ismaster' 2>/dev/null`" == "true" ]
       then
         Master=$Server
+      else
+        if [ "`${MONGO_CMD} --host $Server -u '<%= p("root_username") %>' \
+            -p '<%= p("root_password") %>' --authenticationDatabase admin \
+            ${MONGO_CMD_PARAM} --eval 'db.isMaster().ismaster' 2>/dev/null`" == "true" ]
+        then
+          Master=$Server
+        fi
       fi
-    fi
-  done
-  echo $Master
+    done
+    echo $Master
 }
+################################################################################################
 
+######################### Removing nodes that are not in cluster (scale out) ###################
 remove_unwanted_nodes()
 {
-  export MONGO_CMD_PARAM="${MONGO_CMD_PARAM} \
-    -u <%= p("root_username") %> -p <%= p("root_password") %> --authenticationDatabase admin"
+    export MONGO_CMD_PARAM="${MONGO_CMD_PARAM} \
+      -u <%= p("root_username") %> -p <%= p("root_password") %> --authenticationDatabase admin"
 
-  wanted_servers=$(echo <%= mongo_rsconfig -%>|tr -s "," " ")
-  for defined_server in $( get_actual_members )
-  do
-    if [ `echo $wanted_servers| grep $defined_server|wc -l` -eq 0 ]
-    then
-      ${MONGO_CMD} --host <%= p("replication.replica_set_name") %>/$Master \
-        ${MONGO_CMD_PARAM} --eval 'rs.remove("'$defined_server':<%= mongo_DbTypeport %>")'
-    fi
-  done
-}
-
-create_admin_users()
-{
-     # check if admin users have already been created
-    CR=1
-    while [ $CR -ne 0 ]
+    wanted_servers=$(echo <%= mongo_rsconfig -%>|tr -s "," " ")
+    for defined_server in $( get_actual_members )
     do
-      created=`${MONGO_CMD} ${MONGO_CMD_PARAM} --host <%= mongo_current_ip %> \
-        --eval 'db.getUser("<%= p("admin_username") %>")' admin`
-      CR=$?
-      [ $CR -eq 0 -a "$created" == "null" ] && CR=1
-      if [ $CR -eq 0 ]
+      if [ `echo $wanted_servers| grep $defined_server|wc -l` -eq 0 ]
       then
-        created=`${MONGO_CMD} ${MONGO_CMD_PARAM} --host <%= mongo_current_ip %> \
-          --eval 'db.getUser("<%= p("root_username") %>")' admin`
-        CR=$?
-        [ $CR -eq 0 -a "$created" == "null" ] && CR=1
-      fi
-      # Create admin users if not already created
-      if [ $CR -ne 0 ]
-      then
-         ${MONGO_CMD} ${MONGO_CMD_PARAM} --host <%= mongo_current_ip %> < /var/vcap/jobs/${JOB_NAME}/js/create_admin_user.js
+        ${MONGO_CMD} --host <%= p("replication.replica_set_name") %>/$Master \
+          ${MONGO_CMD_PARAM} --eval 'rs.remove("'$defined_server':<%= mongo_DbTypeport %>")'
       fi
     done
 }
+################################################################################################
 
-init_rs()
+######################### Create Mongodb Admin and Root users ##################################
+create_admin_users()
+{
+     # check if admin users have already been created
+    created=""
+    while [ "$created" != "null" -o "$created" == "" ]
+    do
+      created=`${MONGO_CMD} ${MONGO_CMD_PARAM} --host <%= mongo_current_ip %>:<%= mongo_DbTypeport %> \
+        --eval 'db.getUser("<%= p("admin_username") %>")' admin 2>/dev/null||echo 1`
+      if [ $(echo "$created"|grep "Error: not master and slaveOk=false"|wc -l) -gt 0 ]
+      then 
+         created=""
+      fi   
+      if [ "$created" != "" -a "$created" != "null" ]
+      then
+        created=`${MONGO_CMD} ${MONGO_CMD_PARAM} --host <%= mongo_current_ip %> \
+          --eval 'db.getUser("<%= p("root_username") %>")' admin||echo 1`        
+      fi      
+    done
+    # Create admin users if not already created
+    if [ "$created" == "null" ]
+    then
+       ${MONGO_CMD} ${MONGO_CMD_PARAM} --host <%= mongo_current_ip %>:<%= mongo_DbTypeport %> < /var/vcap/jobs/${JOB_NAME}/js/create_admin_user.js
+    fi
+}
+################################################################################################
+
+######################### Replicaset initialisation on primary node ############################
+init_primary()
 {
     CR=1
     while [ $CR -ne 0 ]
     do
-      ${MONGO_CMD} --host <%= mongo_current_ip %> \
+      ${MONGO_CMD} --host <%= mongo_current_ip %>:<%= mongo_DbTypeport %> \
         ${MONGO_CMD_PARAM} < /var/vcap/jobs/${JOB_NAME}/js/initiate_rs.js
       CR=$?
     done
     # wait until rs is fully active
-    # while [ `${MONGO_CMD} --host <%= mongo_current_ip %> ${MONGO_CMD_PARAM} --eval 'rs.status().ok'` -ne 1 -o \
-    # $(${MONGO_CMD} --host <%= mongo_current_ip %> ${MONGO_CMD_PARAM} --eval 'rs.status().members'| \
-    # grep "\"infoMessage\" : \"could not find member to sync from\""|wc -l) -gt 0 ]
-    while [ `${MONGO_CMD} --host <%= mongo_current_ip %> ${MONGO_CMD_PARAM} --eval 'rs.status().ok'` -ne 1 ]
+    while [ `${MONGO_CMD} --host <%= mongo_current_ip %>:<%= mongo_DbTypeport %> ${MONGO_CMD_PARAM} --eval 'rs.status().ok'||echo 0` -ne 1 ]
     do
       sleep 3
     done
 }
+################################################################################################
 
-# nodes initialisation in replicaset mode
-start_replicaset()
+########################## Primary node initialization #########################################
+run_replicaset()
 {
-Master=$( check_master )
-if [ "$Master" == "" -o "$Master" == "<%= mongo_current_ip %>" ]
-then
-  [ "$Master" == "" ] && start_bs || remove_unwanted_nodes
-  # check if rs is already initialized
-  if [ "$(${MONGO_CMD} --host <%= mongo_current_ip %> ${MONGO_CMD_PARAM} \
-      --eval 'rs.status().codeName' 2>/dev/null)" == "NotYetInitialized" ]
-  then
-    init_rs
-    create_admin_users
-  fi
-else
-  start_bs
+    Master=$( check_master )
+    if [ "$Master" == "" -o "$Master" == "<%= mongo_current_ip %>:<%= mongo_DbTypeport %>" ]
+    then
+      # check if rs is already initialized
+      if [ "$(${MONGO_CMD} --host <%= mongo_current_ip %>:<%= mongo_DbTypeport %> ${MONGO_CMD_PARAM} \
+          --eval 'rs.status().codeName' || echo 'Err')" == "NotYetInitialized" ]
+      then
+        init_primary          # perform rs.initiate
+        create_admin_users    # Create admin and root users
+      fi
+    else
+      add_secondary
+    fi
+}
+################################################################################################
+
+########################## Adding secondary node to replicaset #################################
+add_secondary()
+{
+  # on secondary nodes, mongod HAVE TO be started with authentication
+  start_mongod_with_auth          # Start mongod with authentication
+
+
+  # At this point primary should be started with authentication too
   export MONGO_CMD_PARAM="${MONGO_CMD_PARAM} -u <%= p("root_username") %> -p <%= p("root_password") %> --authenticationDatabase admin"
-  # check Master node if admin users have already been created
-  admin_initialized=`${MONGO_CMD} --host $Master ${MONGO_CMD_PARAM} \
-    --eval 'db.getUser("<%= p("admin_username") %>")' admin`
-  CR=$?
-  [ $CR -eq 0 -a "$admin_initialized" == "null" ] && CR=1
-  if [ $CR -eq 0 ]
-  then
-    admin_initialized=`${MONGO_CMD} --host $Master  ${MONGO_CMD_PARAM} \
-      --eval 'db.getUser("<%= p("root_username") %>")' admin`
-    CR=$?
-    [ $CR -eq 0 -a "$admin_initialized" == "null" ] && CR=1
-  fi
 
-  if [ $CR -eq 0 ]
-  then
-    # restarting with auth
-    kill_and_wait $PIDFILE
-    pid_guard $PIDFILE ${JOB_NAME}
-    su -m vcap -c "$MONGODB_BIN/mongod --config $MONGODB_CONF/mongod.conf --pidfilepath $PIDFILE"
-  else
-    exit 1
-  fi
+  # if root user is not available, primary has probably not finish his job, wait for it
+  
+  root_initialized=""
+  while [ "$root_initialized" == "" ]
+  do
+    root_initialized=`${MONGO_CMD} --host $Master \
+      ${MONGO_CMD_PARAM} --eval 'db.getUser("<%= p("root_username") %>")' admin||echo "null"`
+    
+    [ "$root_initialized" == "null" ] && sleep 2
+  done
 
-  # Adding current node to rs
-  ${MONGO_CMD} --host <%= p("replication.replica_set_name") %>/$Master \
+   # Adding current node to rs
+  ${MONGO_CMD} --host $Master \
     ${MONGO_CMD_PARAM} --eval 'rs.add("<%= mongo_current_ip %>:<%= mongo_DbTypeport %>")'
+
   [ $? -ne 0 ] && exit 1
   # need to wait for complete add before restarting
   _timeout=30
@@ -223,33 +254,35 @@ else
   while [ "$add_ok" == "false" ]
   do
     add_ok=`${MONGO_CMD} --host <%= mongo_current_ip %>:<%= mongo_DbTypeport %> ${MONGO_CMD_PARAM} \
-      --eval 'rs.isMaster().secondary'`
+      --eval 'rs.isMaster().secondary'||echo "false"`
     if [ "$add_ok" != "true" ]
     then
+      add_ok="false"
       sleep 2
       _timeout=$((_timeout-2))
       [ ${_timeout} -le 0 ] && echo "node <%= mongo_current_ip %>:<%= mongo_DbTypeport %> hasn\'t been added. Timeout reached" && exit 1
     fi
   done
-
-fi
 }
+################################################################################################
 
 
-##################################################################################
-#################               Main                   ###########################
-##################################################################################
-sys_update
+################################################################################################
+#########################               Main                   #################################
+################################################################################################
+
+system_update            # Updating system mandatories
 
 export MONGO_CMD_PARAM="--quiet"
 
+start_mongod_noauth          # Start mongod without authentication
+
 <%- if  p("node_role") == "sa" %>
 # In standalone mode
-start_bs
-create_admin_users
+create_admin_users    # Create the admin and root users
 <%- else -%>
 # In replicaset mode  
-start_replicaset
+run_replicaset
 <%- end -%>
 
 kill_and_wait $PIDFILE
